# Secret d'application. EN PROD : remplacer jwt par une valeur aleatoire :
#   kubectl -n cif create secret generic cif-api-secret \
#     --from-literal=jwt=$(openssl rand -hex 32) --dry-run=client -o yaml | kubectl apply -f -
apiVersion: v1
kind: Secret
metadata:
  name: cif-api-secret
  namespace: cif
type: Opaque
stringData:
  jwt: f44fb65b5bf018efa8fd2057d97e783a0e3ced2245ff81fd41c881554c8b4aa4
